controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /
    controller: App\Controller\HomeController::index

auth_login:
    path: /api/login
    controller: App\Controller\AuthController::login

auth_register:
    path: /api/register
    controller: App\Controller\AuthController::register

logged:
    path: /api/logged
    controller: App\Controller\AuthController::logged

auth_logout:
    path: /api/logout
    controller: App\Controller\AuthController::logout


# -------------------------
# Events

highlighted_events:
    path: /api/highlighted-events
    controller: App\Controller\EventController::highlightedEvents


# -------------------------
# Users

user_profile_update:
    path: /api/user/update/profile
    controller: App\Controller\UserController::updateProfile

user_settings_update:
    path: /api/user/update/settings
    controller: App\Controller\UserController::updateSettings

user_image_update:
    path: /api/user/update/image
    controller: App\Controller\UserController::updateImage