controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

frontend_home:
    path: /fronthome
    controller: App\Controller\FrontendController::redirectToHome

session:
    path: /session-info
    controller: App\Controller\FrontendController::sessionInfo


# -------------------------
# Events
