import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

export const metadata: Metadata = {
  title: "L'agendary - Inscription",
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
